modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="vanilla_additions"
version="1.0.0"
displayName="vanilla additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gosde, MCreator"

[[dependencies.vanilla_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



